export const COMMON = {
  MENUS: {
    CONFIGURATION: "menu-configuration",
    DEPARTMENT: "submenu-department",
    DESIGNATION: "submenu-designation",
    REGION: "submenu-region",
    ZONE: "submenu-zone",
    AREA: "submenu-area",
    BANK_ACCOUNT: "submenu-bank-account",
    FEE_CONFIGURATION: "submenu-fee-configuration",
    AMOUNT_BASED_LOAN_PROPOSAL_APPROVAL: "submenu-amount-based-loan-proposal-approval",
    FUNDING_ORGANIZATION: "submenu-funding-organizations",
    LOAN_FUND: "submenu-loan-fund",
    MFI_PROGRAM: "submenu-mfi-program",
    OFFICE: "menu-office",
    OFFICE_MANAGEMENT: "submenu-office-management",
    MY_TASK: "menu-my-task",
    AWAITING_CALENDAR_YEAR: "submenu-awaiting-calendar-year",
    AWAITING_CLIENT_WELFARE_FUND: "submenu-awaiting-client-welfare-fund",
    AWAITING_EMPLOYEE: "submenu-awaiting-employee",
    AWAITING_EMPLOYEE_MANAGEMENT: "submenu-awaiting-employee-management",
    AWAITING_EMPLOYEE_PROMOTION: "submenu-awaiting-employee-promotion",
    AWAITING_EMPLOYEE_TERMINATION: "submenu-awaiting-employee-termination",
    AWAITING_EMPLOYEE_TRANSFER: "submenu-awaiting-employee-transfer",
    AWAITING_HOLIDAY_APPROVAL: "submenu-awaiting-holiday-approval",
    AWAITING_LOAN_ACCOUNT_PROPOSAL: "submenu-awaiting-loan-account-proposal",
    AWAITING_LOAN_PENALTY: "submenu-awaiting-loan-penalty",
    AWAITING_LOAN_REBATE: "submenu-awaiting-loan-rebate",
    AWAITING_MANUAL_JOURNAL: "submenu-awaiting-manual-journal",
    AWAITING_MEMBER_MANAGEMENT: "submenu-awaiting-member-management",
    AWAITING_MEMBER_SAMITY_TRANSFER: "submenu-awaiting-member-samity-transfer",
    AWAITING_MFI_MANAGEMENT: "submenu-awaiting-mfi-management",
    AWAITING_PAYMENT_VOUCHER: "submenu-awaiting-payment-voucher",
    AWAITING_RECEIVED_VOUCHER: "submenu-awaiting-received-voucher",
    AWAITING_SAMITY_CLOSE: "submenu-awaiting-samity-close",
    AWAITING_SAMITY_DAY_CHANGE: "submenu-awaiting-samity-day-change",
    AWAITING_SAMITY_FIELD_OFFICER_CHANGE: "submenu-awaiting-samity-field-officer-change",
    AWAITING_SAMITY_MANAGEMENT: "submenu-awaiting-samity-management",
    AWAITING_SAVINGS_ACCOUNT_PROPOSAL: "submenu-awaiting-savings-account-proposal",
    PENDING_OFFICE_APPROVAL: "submenu-pending-office-approval",
  },

  KEYS: {
    ENTER: "{enter}",
  },

  BUTTONS: {
    ADD_NEW: "btn-add-new",
    RESET: "btn-reset",
    SUBMIT: "btn-submit",
    GO_BACK: "btn-go-back",
    DRAFT: "btn-draft",
    APPROVE: "btn-approve",
    REFRESH: "btn-refresh",
    SEARCH: "btn-search",
    CANCEL: "btn-cancel",
    EDIT: "btn-edit",
    START_PROCESS: "btn-start-process",
    DELETE: "btn-delete",
    SAVE: "btn-save",
    UNSUBMIT: "btn-unsubmit",
    CHECKBOX: "header-checkbox",
    AUTHORIZE_SAMITY: "row-checkbox-1",
    LOCK: "btn-lock",
    UNLOCK: "btn-unlock",
    AUTHORIZE: "authorize-button",
    AUTHORIZE_SHORT: "btn-authorize",
    AUTHORIZE_UNLOCK: "unlock-button",
    REJECT: "reject-button",
    DAYENDMIS_STARTPROCESS: "btn-start_process",
    DAYENDAIS_PROCESS: "day-end-process-button",
    PREVIEW: "btn-preview",
    AIS_GOBACK: "go-back-button",
    PREVIOUS: "btn-draft-on",
    AIS_SEARCH: "search-button",
    FORWARD: "btn-forward",
    CONFIRM: "btn-confirm",
    FORWARD_DELETE: "delete-button",
    CANCEL_MULTIPLE: "btn-cancel-multiple",
    RESTORE_MULTIPLE: "btn-restore-multiple",
    RESTORE: "btn-restore-2",
    CANCEL_SAMITY: "btn-cancel-2",
    SELECT_ALLCHECKBOX: "check-select-all",
    CHECK_SAMITY: "check-samity-2",
    TURN_EDIT_MODE: "switch-button",
    PROFILE: "profile-menu",
    LANGUAGE_CHANGE: "btn-lang-bangla",
    LOGOUT: "btn-logout",
    MODULE_SWITCHER: "module-switcher",
    BACK: "btn-back",
    ADD: "btn-add",
    UPDATE: "btn-update",
    RELOAD: "btn-reload",
    VIEW_REPORT: "btn-view-report",
    MODAL_SUBMIT: "btn-modal-submit",
    LOAN_DISBURSE: "btn-loan-disburse",
    APPROVE_CAPITALIZED: "btn-Approve",
    REJECT_LOWERCASE: "btn-reject",
    REJECT_CAPITALIZED: "btn-Reject",
    PREVIEW_REPAYMENT_SCHEDULE: "btn-preview-repay-schedule",
    ADD_GUARANTOR: "btn-add-guarantor",
    REMOVE_GUARANTOR: "btn-remove-guarantor",
    ADD_ICON: "btn-add-icon",
    REMOVE_ICON: "btn-remove-icon",
    ADD_ICON_FIRST: "btn-add-icon-0",
    REMOVE_ICON_SECOND: "btn-remove-icon-1",
    ADD_METHOD_FIRST: "btn-add-method-0",
    REMOVE_METHOD_FIRST: "btn-remove-method-0",
    ADD_ICON_BUTTON_KEBAB: "add-icon-button",
    REMOVE_ICON_BUTTON_KEBAB: "remove-icon-button",
    ADD_ICON_BUTTON_CAMEL: "addIconButton",
    REMOVE_ICON_BUTTON_CAMEL: "removeIconButton",
  },

  GRID: {
    ACTION_TOGGLE: "toggle-action",
    ACTION_VIEW: "btn-table-action-view",
    ACTION_EDIT: "btn-table-action-edit",
    ACTION_DELETE: "btn-table-action-delete",
    ACTION_SUBMIT: "btn-table-action-submit",
    ACTION_RESET: "btn-table-action-reset",
    ACTION_UNSUBMIT: "btn-table-action-unsubmit",
    ACTION_OPEN: "btn-table-action-open",
    ACTION_MIS_CHANGE: "btn-mis-table-action-change",
    ACTION_MIS_CLOSE: "btn-mis-table-action-close",
    ACTION_MIS_EDIT: "btn-mis-table-action-edit",
    ACTION_MIS_PROFILE: "btn-mis-table-action-profile",
    ACTION_MIS_TRANSFER: "btn-mis-table-action-transfer",
    ACTION_CLOSE: "btn-table-action-close",
    ACTION_DISBURSE: "btn-table-action-disburse",
    ACTION_PROFILE: "btn-table-action-profile",
    ACTION_PROMOTION: "btn-table-action-promotion",
    ACTION_TERMINATION: "btn-table-action-termination",
    ACTION_TRANSFER: "btn-table-action-transfer",
    ACTION_VERIFY: "btn-table-action-verify",
    DRAFT_TOGGLE: "btn-draft-table",
    HISTORY_TOGGLE: "btn-history-table",
    ROW: "table-row",
    FIRST_ROW: "table-row-first",
  },

  CONFIRMATION: {
    YES: "btn-yes",
    NO: "btn-no",
    OK: "btn-ok",
  },

  INPUTS: {
    SEARCH_TEXT: "search_text",
    STATUS_DROPDOWN: "status",
    NAME_EN: "name_en",
    NAME_BN: "name_bn",
    SHORT_NAME: "short_name",
    DESCRIPTION_EN: "descriptionEn",
    DESCRIPTION_BN: "descriptionBn",
    DESIGNATION_NAME_EN: "emp_designation_en",
    DESIGNATION_NAME_BN: "emp_designation_bn",
    DESIGNATION_SHORT_NAME: "emp_designation_short_name",
    SEARCH_IMS: "input-search",
    AMOUNT_IMS: "amount-input",
    LOAN_FIRST: "loan-input-0",
    AMOUNT_FIRST: "input-1",
    APPROVER_REMARKS: "approver-remarks-textarea",
  },

  TOGGLES: {
    ACTION: "toggle-action",
  },

  DROPDOWNS: {
    ACTIVE: "Active",
    INACTIVE: "Inactive",
    APPROVE: "Approve",
    REJECT: "Reject",
    PENDING: "pending",
  },

  TABLE: {
    ROW: "table-row",
    FIRST_ROW: "table-row-first",
    HEAD: "thead",
    HEADER_CELL: "th",
    BODY: "tbody",
    VISIBLE_ROW: "tr:not(.ant-table-placeholder):visible",
    VISIBLE_ROWS: "tbody tr:not(.ant-table-placeholder):visible",
    VISIBLE_CELLS: "td",
    ACTION_TOGGLE: "[data-ims-id='toggle-action']",
  },

  PAGINATION: {
    CONTAINER: ".ant-pagination",
    OPTIONS: ".ant-pagination-options",
    PAGE_SIZE_SELECT: ".ant-pagination-options .ant-select",
    TOTAL_TEXT: ".ant-pagination-total-text",
    ACTIVE_PAGE: ".ant-pagination-item-active",
    PAGE_ITEMS: ".ant-pagination-item",
    NEXT_PAGE: ".ant-pagination-next",
    PREVIOUS_PAGE: ".ant-pagination-prev",
    DISABLED_CLASS: "ant-pagination-disabled",
  },

  SELECT: {
    OPTION: ".ant-select-item-option",
    VISIBLE_DROPDOWN: ".ant-select-dropdown:visible",
  },

  SORT: {
    ATTRIBUTE: "aria-sort",
    ASCENDING: "ascending",
    DESCENDING: "descending",
    ACTIVE_CLASS: "ant-table-column-sort",
  },

  FORM: {
    ITEM: ".ant-form-item",
    LABEL: "label",
    REQUIRED_LABEL_CLASS: "ant-form-item-required",
    INVALID_CONTROL_CLASS: "ng-invalid",
    VIEW_FIELDS: "input:visible, textarea:visible",
  },

  PAGE: {
    BODY: "body",
    VISIBLE_ELEMENT: ":visible",
  },

  CHECKBOXES: {
    GENERIC: "ck-box",
    FIRST: "checkbox-1",
    ROW_0: "row-checkbox-0",
    ROW_1: "row-checkbox-1",
    ROW_2: "row-checkbox-2",
    ROW_3: "row-checkbox-3",
    ROW_4: "row-checkbox-4",
    ROW_6: "row-checkbox-6",
    ROW_7: "row-checkbox-7",
    ROW_9: "row-checkbox-9",
  },

  UPLOADS: {
    PHOTO: "btn_photo_image_id",
    NID_FRONT: "btn_nid_front_doc_id",
    NID_BACK: "btn_nid_back_doc_id",
    BIRTH_REGISTRATION: "btn_birth_reg_doc_id",
    PASSPORT: "btn_passport_doc_id",
    DRIVING_LICENSE: "btn_driving_license_doc_id",
    OTHER_ID: "btn_other_id_doc_id",
    TIN: "btn_tin_doc_id",
  },

  LOAN_CHART: {
    MIN_OVERDUE_DAY_6: "min-over-due-day-6",
    MAX_OVERDUE_DAY_6: "max-over-due-day-6",
    ACCUMULATION_RATE_6: "accumulation-rate-6",
    MIN_OVERDUE_DAY_7: "min-over-due-day-7",
    MAX_OVERDUE_DAY_7: "max-over-due-day-7",
    ACCUMULATION_RATE_7: "accumulation-rate-7",
  },

  AUTH: {
    USER_NAME: "user-name-container",
  },

  DEPARTMENT: {
    CREATE_PATH: "/department/create",
    COLUMNS: {
      NUMBER: 0,
      NAME_EN: 1,
      NAME_BN: 2,
      DEPARTMENT_ID: 3,
      STATUS: 4,
    },
  },

};
