export const COMMON = {
  BUTTONS: {
    ADD_NEW: "btn-add-new",
    RESET: "btn-reset",
    SUBMIT: "btn-submit",
    GO_BACK: "btn-go-back",
    DRAFT: "btn-draft",
    APPROVE: "btn-approve",
    REFRESH: "btn-refresh",
    SEARCH: "btn-search",
    CANCEL: "btn-cancel",
    EDIT: "btn-edit",
    START_PROCESS: "btn-start-process",
    DELETE: "btn-delete",
    SAVE: "btn-save",
    UNSUBMIT: "btn-unsubmit",
    CHECKBOX: "header-checkbox",
    AUTHORIZE_SAMITY: "row-checkbox-1",
    LOCK: "btn-lock",
    UNLOCK: "btn-unlock",
    AUTHORIZE: "authorize-button",
    AUTHORIZE_UNLOCK: "unlock-button",
    REJECT: "reject-button",
    DAYENDMIS_STARTPROCESS: "btn-start_process",
    DAYENDAIS_PROCESS: "day-end-process-button",
    PREVIEW: "btn-preview",
    AIS_GOBACK: "go-back-button",
    PREVIOUS: "btn-draft-on",
    AIS_SEARCH: "search-button",
    FORWARD: "btn-forward",
    CONFIRM: "btn-confirm",
    FORWARD_DELETE: "delete-button",
    CANCEL_MULTIPLE: "btn-cancel-multiple",
    RESTORE_MULTIPLE: "btn-restore-multiple",
    RESTORE: "btn-restore-2",
    CANCEL_SAMITY: "btn-cancel-2",
    SELECT_ALLCHECKBOX: "check-select-all",
    CHECK_SAMITY: "check-samity-2",
    TURN_EDIT_MODE: "switch-button",
    PROFILE: "profile-menu",
    LANGUAGE_CHANGE: "btn-lang-bangla",
  },

  GRID: {
    ACTION_TOGGLE: "toggle-action",
    ACTION_VIEW: "btn-table-action-view",
    ACTION_EDIT: "btn-table-action-edit",
    ACTION_DELETE: "btn-table-action-delete",
    ACTION_SUBMIT: "btn-table-action-submit",
    ACTION_RESET: "btn-table-action-reset",
    ACTION_UNSUBMIT: "btn-table-action-unsubmit",
    ACTION_OPEN: "btn-table-action-open",
    DRAFT_TOGGLE: "btn-draft-table",
    HISTORY_TOGGLE: "btn-history-table",
    ROW: "table-row",
    FIRST_ROW: "table-row-first",
  },

  CONFIRMATION: {
    YES: "btn-yes",
    NO: "btn-no",
    OK: "btn-ok",
  },

  INPUTS: {
    SEARCH_TEXT: "search_text",
    STATUS_DROPDOWN: "status",
    NAME_EN: "name_en",
    NAME_BN: "name_bn",
    SHORT_NAME: "short_name",
    DESCRIPTION_EN: "descriptionEn",
    DESCRIPTION_BN: "descriptionBn",

  },

  TOGGLES: {
    ACTION: "toggle-action",
  },

  DROPDOWNS: {
    ACTIVE: "Active",
    INACTIVE: "Inactive",
    APPROVE: "Approve",
    REJECT: "Reject",
    PENDING: "pending",
  },

  TABLE: {
    ROW: "table-row",
    FIRST_ROW: "table-row-first",
  },
};
